### PR TITLE
Several improvements.

### PR DESCRIPTION
**Pull request by cmars**
Build for xenial, enable systemd service.
Break up installation process, made idempotent: ufw setup,
easy-rsa.
Using template for server config file.
Config options for subnet, DNS servers.
Updated icon.svg to the OpenVPN logo.
git & Makefile improvements: remove JUJU_REPOSITORY, ignore build directories,
vim swapfiles. .PHONY next to target is easier to maintain.
Use layer:apt to install deps.
Detect which network interface is used for public IP. Might not be
called eth0.

### CODE REVIEW

**Comment by cmars** [comment]
Tested VPN successfully with GCE. Next step is to improve the client ovpn.

**Comment by mattyw** [comment]
Thanks for this @cmars it looks amazing. I wasn't actually able to get access to vpn when deployed on ec2 using the certs provided by make client. Any ideas?

**Review by mattyw — APPROVED** [review]
LGTM - will land once I can work out why I can't connect

**Comment by mattyw** [comment]
@cmars I got it working so I'll land it, however there seems to be a bug:
```
● openvpn.service - OpenVPN service
   Loaded: loaded (/lib/systemd/system/openvpn.service; enabled; vendor preset: enabled)
   Active: active (exited) since Sun 2016-12-04 16:02:15 UTC; 4min 14s ago
  Process: 12927 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 12927 (code=exited, status=0/SUCCESS)
```

openvpn seems to start then exit, if I run it from the command line it's fine:
```
sudo openvpn --config /etc/openvpn/server.conf
```

**Pull request merged**
