### PR TITLE
Makefile: Allow custom named profiles

### PR DESCRIPTION
**Pull request by mattyw**
CLIENT=name make ovpn

Allows you to make a profile with name

### CODE REVIEW

**Comment by mattyw** [comment]
@cmars PTAL

**Review by cmars — APPROVED** [review]
LGTM. Could also possibly default UNIT to `juju status --format json | jq -r '.applications["openvpn"].units|keys|.[]' | head -1`

**Comment by mattyw** [comment]
@cmars aha, I was trying to work out the magic runes, PTAL

**Review by cmars — APPROVED** [review]
:shipit:

**Pull request merged**
